services:
  pgAdmin:
    image: dpage/pgadmin4
    container_name: pgAdmin
    environment:
      - PGADMIN_DEFAULT_EMAIL="${PGADMIN_DEFAULT_EMAIL}"
      - PGADMIN_DEFAULT_PASSWORD="${PGADMIN_DEFAULT_PASSWORD}"
    ports:
      -"8085:80"
    networks:
      - app-network
  
  postgres:
    image: postgres:15
    container_name: postgresdb
    restart: always
    environment: 
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
  
  frontend:
    build: ./frontend
    container_name: frontVue
    environment:
      - VUE_APP_API_URL=http://192.188.53.214:8081/api
    ports:
      - "8080:80"
    networks:
      - app-network
    depends_on:
      - backend

  backend:
    build: ./backend
    container_name: backAPI
    restart: always
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresdb:5432/${POSTGRES_DB}
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "8081:8080"
    networks:
      - app-network
    depends_on:
      - postgresdb

network:
  app-network:
    driver: bridge

